### ISSUE TITLE
Enhancement Request: ROM Explorer: Implement folders

### ISSUE THREAD

**Issue by SanPollo** [TomDDG/ZXPicoZXCx#5]
ROM Explorer is an amazing program, but it's very easy to get carried away and upload too many ROMs, making it time consuming to navigate to the one you want to use.

Please implement folders and subfolders so that ROMs can be better organised.

**Comment by TomDDG** [comment]
Thanks for the suggestion. The number of ROMs is limited by the flash size which is the main reason I didn't go with folders as you can only get a limited number loaded. I am working on a new version that uses a SD Card and this will allow folders.
