### ISSUE TITLE
I missed a debug port short when soldering my Pico directly on the ZXPicoIF2Lite pins.

### ISSUE THREAD

**Issue by imatic-preclik** [TomDDG/ZXPicoZXCx#6]
![IMG_20240923_0931171](https://github.com/user-attachments/assets/1f89f80e-47d8-45c5-9160-527c69778a45)

I'm stuck now. File it? There is no gap to shim something between...

**Comment by TomDDG** [comment]
The PCB is designed to mount the PICO via a socket so the via's don't clash. I also haven't tidied up the via placements so will bear this in mind for future releases.

I would highly recommend not filing the Pico and if you want to mount direct just put some kapton tape down first.
